/**
 * Reverse-proxy (Traefik) dynamic-config writer for project domains.
 *
 * Slipway routes domains by writing one dynamic file per project-domain into
 * the directory Traefik's file provider watches. The filename matches the
 * existing incident shape (`app-<slug>-<id>.yml`) so host-health's watcher
 * diagnosis still lines up.
 *
 * Where the directory lives:
 *   - SLIPWAY_TRAEFIK_DYNAMIC_DIR when set (production), else
 *   - <SLIPWAY_DATA_DIR or ./data>/traefik/dynamic (local/dev).
 * In the container the directory should be a volume shared with Traefik
 * (see docker-compose.traefik.yml). Writing is best-effort: if the dir is
 * unreachable the domain row is still persisted and the failure is logged —
 * we do not fake that routing happened.
 */
import { promises as fs } from "node:fs"
import path from "node:path"

export interface DomainRouteInput {
  projectSlug: string
  projectId: string
  hostname: string
  /** container port the app listens on */
  targetPort: number
  /** domain mode: letsencrypt | selfsigned | http */
  tls: "letsencrypt" | "selfsigned" | "http"
}

function dynamicDir(): string {
  const explicit = process.env.SLIPWAY_TRAEFIK_DYNAMIC_DIR?.trim()
  if (explicit) return explicit
  const base = process.env.SLIPWAY_DATA_DIR?.trim() || path.join(process.cwd(), "data")
  return path.join(base, "traefik", "dynamic")
}

function isIp(host: string): boolean {
  return /^(\d{1,3}\.){3}\d{1,3}$/.test(host) || host.includes(":")
}

/**
 * Write the Traefik router+service for a project domain. Returns the file
 * path on success, throws on failure so the caller can record the domain as
 * `pending` and surface the reason (no fake "routed").
 */
export async function writeDomainRoute(input: DomainRouteInput): Promise<string> {
  const dir = dynamicDir()
  await fs.mkdir(dir, { recursive: true })
  const slug = input.projectSlug.replace(/[^a-z0-9-]/gi, "-").toLowerCase()
  const routerName = `slipway-${slug}-${input.projectId.slice(-6)}`.replace(/[^a-z0-9-]/gi, "-")
  const serviceName = `${routerName}-svc`
  const isTls = input.tls !== "http"
  const hostRule = isIp(input.hostname)
    ? `Host(\`${input.hostname}\`)`
    : `Host(\`${input.hostname}\`)`

  const lines: string[] = [
    "# Generated by Slipway — do not edit",
    "http:",
    "  routers:",
    `    ${routerName}:`,
    `      rule: "${hostRule}"`,
    `      service: ${serviceName}`,
    `      entryPoints: [${isTls ? "websecure" : "web"}]`,
  ]
  if (input.tls === "letsencrypt") {
    lines.push("      tls:", "        certResolver: letsencrypt")
  } else if (input.tls === "selfsigned") {
    // Traefik serves its default cert; no ACME (public CAs don't issue for IPs)
    lines.push("      tls: {}")
  }
  lines.push(
    "  services:",
    `    ${serviceName}:`,
    "      loadBalancer:",
    "        servers:",
    `          - url: "http://127.0.0.1:${input.targetPort}"`,
    "        passHostHeader: true"
  )
  const file = path.join(dir, `app-${slug}-${input.projectId.slice(-6)}.yml`)
  await fs.writeFile(file, lines.join("\n") + "\n", "utf8")
  return file
}

/** Remove a project's dynamic file (domain delete / project delete). */
export async function removeDomainRoute(projectSlug: string, projectId: string): Promise<void> {
  const dir = dynamicDir()
  const slug = projectSlug.replace(/[^a-z0-9-]/gi, "-").toLowerCase()
  const file = path.join(dir, `app-${slug}-${projectId.slice(-6)}.yml`)
  await fs.unlink(file).catch(() => {})
}

/**
 * The server's public IP for sslip.io generation. Reads SLIPWAY_PUBLIC_HOST
 * first; refuses loopback/private ranges so sslip never embeds 127.0.0.1.
 */
export function publicIp(): string | null {
  const raw = process.env.SLIPWAY_PUBLIC_HOST?.trim() || ""
  if (!raw) return null
  const host = raw.replace(/^https?:\/\//, "").split("/")[0].split(":")[0]
  if (isPrivateIp(host)) return null
  return isIp(host) ? host : null
}

export function isPrivateIp(host: string): boolean {
  const m = host.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)$/)
  if (!m) return false
  const a = Number(m[1])
  const b = Number(m[2])
  return (
    a === 10 ||
    a === 127 ||
    (a === 172 && b >= 16 && b <= 31) ||
    (a === 192 && b === 168) ||
    (a === 169 && b === 254)
  )
}

/** Build an sslip.io hostname from a public IP. */
export function sslipHostname(slug: string, ip: string): string {
  const dashed = ip.trim().replace(/\./g, "-")
  return `${slug}.${dashed}.sslip.io`
}
