/**
 * Reverse-proxy (Traefik) dynamic-config writer for project domains.
 *
 * Slipway routes domains by writing one dynamic file per project-domain into
 * the directory Traefik's file provider watches. The filename matches the
 * existing incident shape (`app-<slug>-<id>.yml`) so host-health's watcher
 * diagnosis still lines up.
 *
 * Where the directory lives:
 *   - SLIPWAY_TRAEFIK_DYNAMIC_DIR when set (production), else
 *   - <SLIPWAY_DATA_DIR or ./data>/traefik/dynamic (local/dev).
 * In the container the directory should be a volume shared with Traefik
 * (see docker-compose.traefik.yml). Writing is best-effort: if the dir is
 * unreachable the domain row is still persisted and the failure is logged —
 * we do not fake that routing happened.
 *
 * P5 (OpenShip HTTP-01 property, adapted for Traefik): when tls=letsencrypt,
 * also register an HTTP (web) router for the same Host so ACME HTTP-01 and
 * plain HTTP reach the app even while the cert is still pending. Cert failure
 * must never take the HTTP route down.
 */
import { promises as fs } from "node:fs"
import { accessSync } from "node:fs"
import path from "node:path"
import { validIp, isPrivateIp } from "./security"

export { isPrivateIp, validIp }

export interface DomainRouteInput {
  projectSlug: string
  projectId: string
  hostname: string
  /** container port the app listens on */
  targetPort: number
  /** domain mode: letsencrypt | selfsigned | http */
  tls: "letsencrypt" | "selfsigned" | "http"
}

function dynamicDir(): string {
  // Bug 1 (root): the config must land where TRAEFIK actually reads it, not in
  // Slipway's own volume. Precedence:
  //   1. SLIPWAY_TRAEFIK_DYNAMIC_DIR — explicit operator override.
  //   2. /etc/dokploy/traefik/dynamic — the Dokploy host path Traefik watches
  //      (this deployment's proxy). Mounted into the Slipway container via a
  //      host bind (see docker-compose.yml).
  //   3. <SLIPWAY_DATA_DIR or ./data>/traefik/dynamic — local/dev fallback.
  const explicit = process.env.SLIPWAY_TRAEFIK_DYNAMIC_DIR?.trim()
  if (explicit) return explicit
  const dokploy = "/etc/dokploy/traefik/dynamic"
  try {
    accessSync(dokploy)
    return dokploy
  } catch {
    const base = process.env.SLIPWAY_DATA_DIR?.trim() || path.join(process.cwd(), "data")
    return path.join(base, "traefik", "dynamic")
  }
}

function isIp(host: string): boolean {
  // R5: octet-range-checked via net.isIP — the old ^(\d{1,3}\.){3}\d{1,3}$
  // matched 999.999.999.999, which would then be routed/trusted as an "IP".
  return validIp(host)
}

/**
 * Pure Traefik dynamic YAML for a domain route (P5 HTTP-01: dual routers for
 * letsencrypt). Exported for the self-check — writeDomainRoute persists this.
 */
export function renderDomainRouteYaml(input: DomainRouteInput): string {
  const slug = input.projectSlug.replace(/[^a-z0-9-]/gi, "-").toLowerCase()
  const routerName = `slipway-${slug}-${input.projectId.slice(-6)}`.replace(/[^a-z0-9-]/gi, "-")
  const serviceName = `${routerName}-svc`
  const hostRule = `Host(\`${input.hostname}\`)`

  const lines: string[] = [
    "# Generated by Slipway — do not edit",
    "http:",
    "  routers:",
  ]
  if (input.tls === "letsencrypt") {
    // HTTP router first (ACME HTTP-01 + reachable while cert pending).
    // P5 OpenShip property adapted for Traefik — see THIRD-PARTY/NOTICES.
    lines.push(
      `    ${routerName}-http:`,
      `      rule: "${hostRule}"`,
      `      service: ${serviceName}`,
      "      entryPoints: [web]",
      `    ${routerName}:`,
      `      rule: "${hostRule}"`,
      `      service: ${serviceName}`,
      "      entryPoints: [websecure]",
      "      tls:",
      "        certResolver: letsencrypt"
    )
  } else if (input.tls === "selfsigned") {
    lines.push(
      `    ${routerName}:`,
      `      rule: "${hostRule}"`,
      `      service: ${serviceName}`,
      "      entryPoints: [websecure]",
      // Traefik serves its default cert; no ACME (public CAs don't issue for IPs)
      "      tls: {}"
    )
  } else {
    lines.push(
      `    ${routerName}:`,
      `      rule: "${hostRule}"`,
      `      service: ${serviceName}`,
      "      entryPoints: [web]"
    )
  }
  lines.push(
    "  services:",
    `    ${serviceName}:`,
    "      loadBalancer:",
    "        servers:",
    `          - url: "http://127.0.0.1:${input.targetPort}"`,
    "        passHostHeader: true"
  )
  return lines.join("\n") + "\n"
}

/**
 * Write the Traefik router+service for a project domain. Returns the file
 * path on success, throws on failure so the caller can record the domain as
 * `pending` and surface the reason (no fake "routed").
 */
export async function writeDomainRoute(input: DomainRouteInput): Promise<string> {
  const dir = dynamicDir()
  await fs.mkdir(dir, { recursive: true })
  const slug = input.projectSlug.replace(/[^a-z0-9-]/gi, "-").toLowerCase()
  const file = path.join(dir, `app-${slug}-${input.projectId.slice(-6)}.yml`)
  await fs.writeFile(file, renderDomainRouteYaml(input), "utf8")
  return file
}

/** Remove a project's dynamic file (domain delete / project delete). */
export async function removeDomainRoute(projectSlug: string, projectId: string): Promise<void> {
  const dir = dynamicDir()
  const slug = projectSlug.replace(/[^a-z0-9-]/gi, "-").toLowerCase()
  const file = path.join(dir, `app-${slug}-${projectId.slice(-6)}.yml`)
  await fs.unlink(file).catch(() => {})
}

/**
 * The server's public IP for sslip.io generation. Reads SLIPWAY_PUBLIC_HOST
 * first; refuses loopback/private ranges so sslip never embeds 127.0.0.1.
 */
export function publicIp(): string | null {
  const raw = process.env.SLIPWAY_PUBLIC_HOST?.trim() || ""
  if (!raw) return null
  const host = raw.replace(/^https?:\/\//, "").split("/")[0].split(":")[0]
  if (isPrivateIp(host)) return null
  return isIp(host) ? host : null
}

/** Build an sslip.io hostname from a public IP. */
export function sslipHostname(slug: string, ip: string): string {
  const dashed = ip.trim().replace(/\./g, "-")
  return `${slug}.${dashed}.sslip.io`
}
