/**
 * Stack detection + Dockerfile generation — pure and dependency-free so the
 * self-check can cover it without a clone on disk.
 *
 * The "Detect stack" pipeline step used to be `await sleep(300)`, and a repo
 * without a Dockerfile could not be built at all: the pipeline ran
 * `docker build <context>` and failed with "lstat Dockerfile: no such file or
 * directory". Most public repos don't ship a Dockerfile, so that meant most
 * public repos couldn't be deployed.
 *
 * Detection reads only the repository's root listing plus package.json, which
 * is exactly what the pipeline can cheaply collect after a shallow clone.
 */

export type DetectedStack =
  | "dockerfile"
  | "nextjs"
  | "node"
  | "bun"
  | "static"
  | "python"
  | "go"
  | "rust"
  | "ruby"
  | "php"

export interface DetectionInput {
  /** File and directory names at the build context root. */
  files: string[]
  /** Parsed package.json, when one exists at the root. */
  packageJson?: {
    scripts?: Record<string, string>
    dependencies?: Record<string, string>
    devDependencies?: Record<string, string>
    main?: string
    packageManager?: string
  } | null
}

export interface Detection {
  stack: DetectedStack
  /** Human label stored on the project and shown in the UI. */
  label: string
  /** Port the generated image listens on. */
  port: number
  /**
   * Dockerfile to write into the context, or null when the repo ships its own
   * and we must not overwrite it.
   */
  dockerfile: string | null
  /** Why this stack was chosen — surfaced in the deploy step log. */
  reason: string
}

const has = (files: string[], name: string) =>
  files.some((f) => f.toLowerCase() === name.toLowerCase())

/**
 * Node images are pinned to an LTS line rather than `latest` so a rebuild six
 * months from now doesn't silently jump a major version.
 */
const NODE_IMAGE = "node:22-alpine"

/** A repo's own Dockerfile always wins — we never overwrite what it ships. */
function ownDockerfile(): Detection {
  return {
    stack: "dockerfile",
    label: "Dockerfile",
    port: 0, // read from the built image's EXPOSE
    dockerfile: null,
    reason: "The repository ships its own Dockerfile — building that as-is.",
  }
}

function nextJs(pm: PackageManager): Detection {
  return {
    stack: "nextjs",
    label: "Next.js",
    port: 3000,
    reason: "package.json depends on next.",
    dockerfile: `# Generated by Slipway — Next.js
FROM ${NODE_IMAGE} AS deps
WORKDIR /app
COPY package.json ${pm.lockGlob} ./
RUN ${pm.install}

FROM ${NODE_IMAGE} AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN ${pm.run} build

FROM ${NODE_IMAGE} AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
# Next writes .next/standalone only when output:"standalone" is configured.
# Copying the whole build output works for both configurations.
COPY --from=builder /app ./
EXPOSE 3000
CMD ["${pm.bin}", "run", "start"]
`,
  }
}

function nodeApp(pm: PackageManager, hasBuild: boolean, start: string): Detection {
  return {
    stack: pm.bin === "bun" ? "bun" : "node",
    label: pm.bin === "bun" ? "Bun" : "Node.js",
    port: 3000,
    reason: `package.json with a "${start}" script.`,
    dockerfile: `# Generated by Slipway — ${pm.bin === "bun" ? "Bun" : "Node.js"}
FROM ${pm.image} AS builder
WORKDIR /app
COPY package.json ${pm.lockGlob} ./
RUN ${pm.install}
COPY . .
${hasBuild ? `RUN ${pm.run} build\n` : ""}
FROM ${pm.image}
WORKDIR /app
ENV NODE_ENV=production
ENV PORT=3000
ENV HOST=0.0.0.0
COPY --from=builder /app ./
EXPOSE 3000
CMD ["${pm.bin}", "run", "${start}"]
`,
  }
}

function staticSite(): Detection {
  return {
    stack: "static",
    label: "Static site",
    port: 80,
    reason: "index.html at the root and no package.json — serving it with nginx.",
    dockerfile: `# Generated by Slipway — static site
FROM nginx:alpine
COPY . /usr/share/nginx/html
EXPOSE 80
`,
  }
}

function python(files: string[]): Detection {
  const installs = has(files, "requirements.txt")
    ? "RUN pip install --no-cache-dir -r requirements.txt"
    : has(files, "pyproject.toml")
      ? "RUN pip install --no-cache-dir ."
      : "RUN true"
  // Prefer an explicit entrypoint the repo actually has.
  const entry = has(files, "main.py") ? "main.py" : has(files, "app.py") ? "app.py" : "main.py"
  return {
    stack: "python",
    label: "Python",
    port: 8000,
    reason: `Python project (${has(files, "requirements.txt") ? "requirements.txt" : "pyproject.toml"}).`,
    dockerfile: `# Generated by Slipway — Python
FROM python:3.12-slim
WORKDIR /app
ENV PYTHONUNBUFFERED=1
ENV PORT=8000
COPY . .
${installs}
EXPOSE 8000
CMD ["python", "${entry}"]
`,
  }
}

function golang(): Detection {
  return {
    stack: "go",
    label: "Go",
    port: 8080,
    reason: "go.mod at the root.",
    dockerfile: `# Generated by Slipway — Go
FROM golang:1.23-alpine AS builder
WORKDIR /src
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /out/app ./...

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /out/app ./app
ENV PORT=8080
EXPOSE 8080
CMD ["./app"]
`,
  }
}

function rust(): Detection {
  return {
    stack: "rust",
    label: "Rust",
    port: 8080,
    reason: "Cargo.toml at the root.",
    dockerfile: `# Generated by Slipway — Rust
FROM rust:1-slim AS builder
WORKDIR /src
COPY . .
RUN cargo build --release

FROM debian:stable-slim
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=builder /src/target/release/ ./
ENV PORT=8080
EXPOSE 8080
CMD ["sh", "-c", "./$(ls -1 | grep -v '\\\\.' | head -1)"]
`,
  }
}

function ruby(): Detection {
  return {
    stack: "ruby",
    label: "Ruby",
    port: 3000,
    reason: "Gemfile at the root.",
    dockerfile: `# Generated by Slipway — Ruby
FROM ruby:3.3-slim
WORKDIR /app
RUN apt-get update && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
COPY Gemfile* ./
RUN bundle install
COPY . .
ENV PORT=3000
EXPOSE 3000
CMD ["sh", "-c", "bundle exec rackup -o 0.0.0.0 -p 3000"]
`,
  }
}

function php(): Detection {
  return {
    stack: "php",
    label: "PHP",
    port: 80,
    reason: "composer.json or index.php at the root.",
    dockerfile: `# Generated by Slipway — PHP
FROM php:8.3-apache
WORKDIR /var/www/html
COPY . .
EXPOSE 80
`,
  }
}

interface PackageManager {
  bin: "npm" | "yarn" | "pnpm" | "bun"
  image: string
  install: string
  run: string
  /** Lockfile glob for the COPY layer; a trailing `*` keeps COPY happy when absent. */
  lockGlob: string
}

/** Pick the package manager from the lockfile the repo actually committed. */
export function detectPackageManager(files: string[]): PackageManager {
  if (has(files, "bun.lockb") || has(files, "bun.lock")) {
    return { bin: "bun", image: "oven/bun:1-alpine", install: "bun install", run: "bun run", lockGlob: "bun.lock*" }
  }
  if (has(files, "pnpm-lock.yaml")) {
    return {
      bin: "pnpm",
      image: NODE_IMAGE,
      install: "corepack enable && pnpm install --frozen-lockfile",
      run: "pnpm",
      lockGlob: "pnpm-lock.yaml*",
    }
  }
  if (has(files, "yarn.lock")) {
    return {
      bin: "yarn",
      image: NODE_IMAGE,
      install: "corepack enable && yarn install --frozen-lockfile",
      run: "yarn",
      lockGlob: "yarn.lock*",
    }
  }
  // npm ci needs a lockfile; fall back to install when the repo has none.
  return {
    bin: "npm",
    image: NODE_IMAGE,
    install: has(files, "package-lock.json") ? "npm ci" : "npm install",
    run: "npm run",
    lockGlob: "package-lock.json*",
  }
}

/**
 * Decide how to build a checked-out repository.
 *
 * Returns null when nothing recognisable is present — the caller then fails
 * with an honest "add a Dockerfile" message rather than guessing.
 */
export function detectStack(input: DetectionInput): Detection | null {
  const files = input.files ?? []
  const pkg = input.packageJson

  // 1. The repo's own Dockerfile always wins.
  if (has(files, "Dockerfile")) return ownDockerfile()

  // 2. Node ecosystem, keyed off package.json.
  if (pkg || has(files, "package.json")) {
    const pm = detectPackageManager(files)
    const deps = { ...(pkg?.dependencies ?? {}), ...(pkg?.devDependencies ?? {}) }
    const scripts = pkg?.scripts ?? {}
    if (deps.next || has(files, "next.config.js") || has(files, "next.config.ts") || has(files, "next.config.mjs")) {
      return nextJs(pm)
    }
    const hasBuild = Boolean(scripts.build)
    // Prefer `start`; fall back to `serve`, then `dev` — some repos only ship dev.
    const start = scripts.start ? "start" : scripts.serve ? "serve" : scripts.dev ? "dev" : ""
    if (start) return nodeApp(pm, hasBuild, start)
    // A package.json with a build but no start is almost always a static bundle.
    if (hasBuild) {
      const s = staticSite()
      return {
        ...s,
        reason: "package.json has a build script but no start script — building it and serving the output with nginx.",
        dockerfile: `# Generated by Slipway — static build output
FROM ${pm.image} AS builder
WORKDIR /app
COPY package.json ${pm.lockGlob} ./
RUN ${pm.install}
COPY . .
RUN ${pm.run} build

FROM nginx:alpine
# Vite/CRA/Astro/SvelteKit all emit one of these; copy whichever exists.
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
`,
      }
    }
  }

  // 3. Everything else, keyed off a marker file.
  if (has(files, "requirements.txt") || has(files, "pyproject.toml") || has(files, "Pipfile")) return python(files)
  if (has(files, "go.mod")) return golang()
  if (has(files, "Cargo.toml")) return rust()
  if (has(files, "Gemfile")) return ruby()
  if (has(files, "composer.json") || has(files, "index.php")) return php()

  // 4. Plain static site.
  if (has(files, "index.html")) return staticSite()

  return null
}
